import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Target,BriefcaseBusiness,Users,Truck,ContactRound,Wheat,CheckSquare,CalendarDays,FolderOpen,Network,Handshake,LineChart,BarChart3,Settings,UserCircle2,CircleHelp,Search,Bell,Plus,ChevronRight,Globe2,FileText,Clock3,MapPin,Building2,Filter,ArrowUpRight,PackageCheck,Activity} from 'lucide-react';
import './styles.css';

const nav=[
['Dashboard',LayoutDashboard],['Opportunities',Target],['Projects',BriefcaseBusiness],['Buyers',Users],['Suppliers',Truck],['Contacts',ContactRound],['Commodities',Wheat],['Tasks & Follow-ups',CheckSquare],['Meetings',CalendarDays],['Documents',FolderOpen],['Trade Leads',Network],['Immigration & Partners',Handshake],['Market Intelligence',LineChart],['Reports',BarChart3],['Settings',Settings],['Profile',UserCircle2],['Help & Support',CircleHelp]
];
const stats=[['Active Opportunities','18','+3 this week'],['Active Projects','7','2 updated'],['Open Follow-ups','12','4 overdue'],['Meetings This Week','5','View calendar'],['Total Contacts','236','Buyers & suppliers']];
const opportunities=[
['Petroleum Coke Supply to Asia','Petcoke','Yi Nan Wu','Negotiation','$2.8M','Send COA','Sep 25'],
['Lentils to India','Red Lentils','Ashok Kanda','In Discussion','$680K','Confirm specs','Sep 28'],
['Flax Seed to Pakistan','Flax Seed','Irshad Ali Khokar','Contacted','$210K','Send price list','Sep 26'],
['Chickpeas to UAE','Chickpeas','First Mills','Research','$1.1M','Find suppliers','Oct 2'],
['Canadian Gluten-Free Flour','Flour (GF)','Middle East','Proposal Sent','$450K','Follow up','Sep 30'],
['Aluminum Initiative','Aluminum','Confidential','On Hold','—','Await feedback','—']];
const buyers=[['First Mills','Procurement Dept.','Saudi Arabia','Flour, Pulses','Active','Sep 18, 2026'],['Al Rawabi Trading','Hassan Al-Mansoori','UAE','Lentils, Chickpeas','Active','Sep 12, 2026'],['Yi Nan Wu','Yi Nan Wu','China','Petcoke','Active','Sep 10, 2026'],['Markinch Trading','Rajesh Kumar','India','Lentils, Flax','In Discussion','Aug 26, 2026'],['Zakho Trading','Ali Hassan','Iraq','Flour, Grains','Research','Aug 20, 2026'],['Anadolu Gıda','Mehmet Yılmaz','Turkey','Pulses, Grains','New','Sep 15, 2026']];
const suppliers=[['Suncor Energy','Alberta, Canada','Petcoke','Contacted','COA requested'],['Canadian Natural','Alberta, Canada','Petcoke','Research','Follow-up'],['Prairie Grain Co.','Saskatchewan','Lentils, Peas','Qualified','Pricing received'],['Nutrien Ag Solutions','Saskatchewan','Canary Seed, Pulses','Contacted','Awaiting quote'],['Richardson International','Manitoba','Flax, Wheat','Qualified','Good supply'],['Cargill Canada','Multiple','Grains, Oilseeds','Active','Established']];
const contacts=[['Ashok Kanda','Markinch Trading','Director','Buyer','Sep 12, 2026'],['Yi Nan Wu','ELINK','Procurement','Buyer','Sep 10, 2026'],['Tim Gartner','My Future Canada','Consultant','Immigration','Sep 5, 2026'],['Victor Muhia','—','Business Development','Partner','Aug 28, 2026'],['Rajesh Kumar','Rajasthan Network','Director','Buyer','Aug 25, 2026'],['Irshad Ali Khokar','—','Business Contact','Supplier / Partner','Aug 20, 2026'],['Amandeep Kaur','Lights of Peace','Founder','Partner','Aug 18, 2026']];
const commodities=[['Red Lentils','Pulses','G2, clean','$670','USD/MT','4'],['Green Lentils','Pulses','Laird G2','$693','USD/MT','3'],['Chickpeas','Pulses','Kabuli, 9mm+','$720','USD/MT','2'],['Flax Seed','Oilseeds','Food grade','$780','USD/MT','3'],['Canola Seed','Oilseeds','#1 Canada','$650','USD/MT','2'],['Petcoke (Fuel Grade)','Industrial','6.5% S max','$105','USD/MT','2'],['Petcoke (Calcined)','Industrial','0.5% S max','$215','USD/MT','2']];
const tasks=[['Follow up with Suncor (COA)','Petcoke Supply','High','Overdue','Sep 20'],['Prepare handout for B2B Conference','AgriCan','Medium','In Progress','Sep 22'],['Email draft: Brown Flax to Yi Nan','Flax to Pakistan','Medium','Today','Sep 22'],['Research Canadian Beef Suppliers','New Opportunity','Low','Not Started','Sep 23'],['Call: Immigration case update (Victor)','Partners','Medium','Today','Sep 22'],['Get quote for second bag former','Flour Project','High','In Progress','Sep 24']];
const meetings=[['Sep 22, 10:00 AM','Supplier Call – Suncor','Ainu, Michael','Supplier','Teams'],['Sep 23, 11:00 AM','Call – Tim Gartner','Ainu, Tim','Immigration','Phone'],['Sep 24, 2:00 PM','B2B Meeting – Grain Export','Ainu, Ashok Kanda','Buyer','Edmonton'],['Sep 26, 1:00 PM','Follow-up – Yi Nan','Ainu, Yi Nan','Buyer','WhatsApp'],['Sep 28, 10:00 AM','Internal Review – Flour Project','Ainu, Michael','Internal','Office']];
const docs=[['Sugar Petcoke COA.pdf','COA','Petcoke Supply','Sep 18, 2026','1.2 MB'],['Machine Comparison.xlsx','Research','Flour Project','Sep 10, 2026','620 KB'],['Buyer Requirements – Yi Nan.pdf','Specification','Petcoke Supply','Sep 5, 2026','640 KB'],['AgriCan Company Profile.pdf','Presentation','AgriCan','Aug 28, 2026','2.1 MB'],['Meeting Notes – Ashok Kanda.docx','Meeting Notes','Lentils to India','Aug 25, 2026','320 KB'],['GACC Decree 280.pdf','Regulatory','Food Export','Aug 20, 2026','1.4 MB']];
const leads=[['Canadian Beef Buyer','Referral','Pakistan','Beef','New'],['Organic Wheat Inquiry','B3 Event','Turkey','Wheat','Research'],['Pulse Importer','Website','UAE','Lentils, Peas','Research'],['Animal Feed Ingredients','Referral','Egypt','Canola, Flax','New'],['Edible Oil Distributor','Conference','India','Canola Oil','Archived']];
const projects=[['Edmonton Gluten-Free Flour Facility','AgriCan','In Progress','80%','Dec 2026'],['Saskatchewan Resource Initiative','IrisTech','Planning','35%','Mar 2027'],['IrisTech Website Development','IrisTech','In Progress','70%','Sep 2026'],['Healthcare Immigration Funnel','Partners','In Progress','60%','Nov 2026'],['Agricultural Export Development','AgriCan','In Progress','65%','Dec 2026'],['Aluminum / Minerals Initiative','IrisTech','On Hold','20%','TBD'],['Ogilvie Grain Limited Launch','Partners','Planning','40%','Sep 2026']];

function Badge({children}){return <span className="badge">{children}</span>}
function Table({headers,rows}){return <div className="tableWrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===3||j===4?<span className={String(c).includes('Overdue')||String(c).includes('On Hold')?'bad':''}>{c}</span>:c}</td>)}</tr>)}</tbody></table></div>}
function Header({title,subtitle,action='New Record'}){return <div className="pageHead"><div><h1>{title}</h1><p>{subtitle}</p></div><button><Plus size={16}/>{action}</button></div>}
function Dashboard(){return <>
<Header title="Good morning, Ainu" subtitle="Here’s what’s happening across your businesses today." action="Quick Add"/>
<div className="stats">{stats.map((s,i)=><div className="stat" key={s[0]}><div className={'statIcon i'+i}><Activity size={20}/></div><div><small>{s[0]}</small><strong>{s[1]}</strong><em>{s[2]}</em></div></div>)}</div>
<div className="grid2"><section className="card"><h3>Pipeline Overview <span>View all <ChevronRight size={14}/></span></h3><div className="funnel">{[['Identified',26],['Contacted',18],['In Discussion',11],['Proposal Sent',6],['Negotiation',4],['Closed / Won',2]].map((x,i)=><div key={x[0]} style={{width:(100-i*10)+'%'}}>{x[0]} <b>{x[1]}</b></div>)}</div></section>
<section className="card"><h3>Top Active Opportunities <span>View all <ChevronRight size={14}/></span></h3>{opportunities.slice(0,5).map(o=><div className="opp" key={o[0]}><div><b>{o[0]}</b><small>{o[1]} · {o[2]}</small></div><Badge>{o[3]}</Badge><strong>{o[4]}</strong></div>)}</section></div>
<div className="grid3"><section className="card"><h3>Today’s Tasks</h3>{tasks.slice(0,5).map(t=><div className="mini"><CheckSquare size={15}/><div><b>{t[0]}</b><small>{t[1]}</small></div><Badge>{t[3]}</Badge></div>)}</section><section className="card"><h3>Upcoming Meetings</h3>{meetings.slice(0,4).map(m=><div className="mini"><CalendarDays size={15}/><div><b>{m[1]}</b><small>{m[0]} · {m[4]}</small></div></div>)}</section><section className="card"><h3>Recent Activity</h3>{['Quote received – Suncor (Petcoke)','Pricing notes – Ashok Kanda','New supplier added – Prairie Grain Co.','Project updated – Flour Packaging'].map((x,i)=><div className="mini"><Clock3 size={15}/><div><b>{x}</b><small>{i+1}h ago</small></div></div>)}</section></div>
</>}
function GenericPage({name}){
 const configs={
 'Opportunities':['Track and manage all business opportunities from initial lead to close.',['Opportunity','Commodity','Buyer / Contact','Stage','Est. Value','Next Action','Due Date'],opportunities],
 'Projects':['Manage internal projects, initiatives and development plans.',['Project','Business','Status','Progress','Target Date'],projects],
 'Buyers':['Manage potential and existing buyers.',['Company','Contact','Country','Products','Status','Last Contact'],buyers],
 'Suppliers':['Manage suppliers and sourcing options.',['Company','Location','Products','Status','Notes'],suppliers],
 'Contacts':['Your complete business network.',['Name','Company','Role','Category','Last Contact'],contacts],
 'Commodities':['Market information, specifications and related opportunities.',['Commodity','Category','Key Specs','Current Price (Est.)','Unit','Opportunities'],commodities],
 'Tasks & Follow-ups':['Stay on top of action items.',['Task','Related To','Priority','Status','Due Date'],tasks],
 'Meetings':['Schedule and track all meetings.',['Date & Time','Title','Participants','Type','Location'],meetings],
 'Documents':['Store and organize all important files.',['Name','Type','Related To','Date Added','Size'],docs],
 'Trade Leads':['Early-stage opportunities and inquiries.',['Lead','Source','Region','Product','Status'],leads],
 'Immigration & Partners':['Track immigration and partnership opportunities.',['Name','Program / Interest','Status','Last Contact'],[['Tim Gartner','Business Immigration','Active','Sep 5, 2026'],['Victor Muhia','Investor / Partnerships','Active','Aug 26, 2026'],['Healthcare Workers','AHS / Alberta','Research','Aug 20, 2026'],['Pakistan Delegation','Business Immigration','In Discussion','Aug 15, 2026'],['SK Developments','Potential Partner','Active','Aug 10, 2026']]],
 'Market Intelligence':['Commodity prices, news and market reports.',['Commodity','Price','Change','Region','Updated'],[['Red Lentils','$670/MT','+4.2%','Canada','Today'],['Green Lentils','$693/MT','+2.4%','Canada','Today'],['Yellow Peas','$420/MT','+2.1%','Canada','Today'],['Petcoke (Calcined)','$215/MT','+3.7%','Global','Today'],['Petcoke (Fuel Grade)','$105/MT','+1.8%','Global','Today']]],
 'Reports':['Generate and view business reports.',['Report','Scope','Frequency','Last Generated'],[['Opportunity Pipeline','All Businesses','Weekly','Sep 20'],['Project Status','Active Projects','Weekly','Sep 20'],['Contact Activity','CRM','Monthly','Sep 1'],['Market Summary','Commodities','Weekly','Sep 19'],['Task Performance','Operations','Monthly','Sep 1']]],
 'Settings':['Manage users, preferences and system configuration.',['Setting','Description','Status'],[['User Management','Roles & access permissions','Configured'],['Business Units','AgriCan, IrisTech, Partners','Configured'],['Custom Fields','Deal and contact fields','Configured'],['Email Integration','Connect business email','Not Connected'],['Notifications','Alerts and reminders','Enabled'],['Data Export','CSV and report export','Enabled']]],
 'Profile':['Manage your account and personal preferences.',['Field','Value'],[['Name','Ainu Azeem'],['Role','Export Manager'],['Business Units','AgriCan International Inc., IrisTech'],['Timezone','Edmonton (MST/UTC-7)'],['Language','English'],['Notifications','Enabled']]],
 'Help & Support':['Get help and access portal resources.',['Resource','Description'],[['User Guide','Portal navigation and workflow guide'],['Video Tutorials','Short training walkthroughs'],['FAQ','Common questions and answers'],['Contact Support','Technical support request']]]
 };
 const c=configs[name]; return <><Header title={name} subtitle={c[0]} action={name==='Settings'||name==='Profile'||name==='Help & Support'?'Manage':'New Record'}/><section className="card"><div className="toolbar"><div className="searchSmall"><Search size={15}/><input placeholder={'Search '+name.toLowerCase()+'...'}/></div><button className="ghost"><Filter size={15}/> Filter</button></div><Table headers={c[1]} rows={c[2]}/></section></>
}
function App(){const [active,setActive]=useState('Dashboard'); return <div className="app"><aside><div className="brand"><div className="mark"><Globe2 size={27}/></div><div><b>AINU</b><small>BUSINESS COMMAND CENTRE</small></div></div><div className="units">AgriCan International Inc. &nbsp;|&nbsp; IrisTech</div><nav>{nav.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}><I size={17}/>{n}{n==='Tasks & Follow-ups'&&<span className="count">12</span>}</button>)}</nav><div className="sideFoot"><button><Plus size={16}/> Quick Add</button><small>Internal prototype · 2026</small></div></aside><main><header><div className="location"><MapPin size={15}/> Edmonton, CAN</div><div className="search"><Search size={17}/><input placeholder="Search anything..."/></div><Bell size={18}/><div className="user"><div className="avatar">AA</div><div><b>Ainu Azeem</b><small>Export Manager</small></div></div></header><div className="content">{active==='Dashboard'?<Dashboard/>:<GenericPage name={active}/>}</div></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
